# Generated by Django 3.1.7 on 2021-03-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='mathematician',
            options={'verbose_name': 'Математик', 'verbose_name_plural': 'Математики'},
        ),
        migrations.AlterModelOptions(
            name='mathsubjectclass',
            options={'verbose_name': 'Предметный класс', 'verbose_name_plural': 'Предметные классы'},
        ),
        migrations.AlterModelOptions(
            name='studentadvisor',
            options={'verbose_name': 'Студент-Науч', 'verbose_name_plural': 'Студенты-Научи'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
    ]
