# Generated by Django 3.1.7 on 2021-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210316_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathematician',
            name='year_of_degree',
            field=models.IntegerField(null=True, verbose_name='Год получения степени'),
        ),
    ]
