# Generated by Django 3.1.7 on 2021-05-31 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210321_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation_name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Диссертация',
                'verbose_name_plural': 'Диссертации',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='year_of_degree',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год получения степени'),
        ),
        migrations.AddField(
            model_name='mathematician',
            name='dissertation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dissertation'),
        ),
        migrations.CreateModel(
            name='MagazineArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleMag', to='main.article')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mathematician', to='main.magazine')),
            ],
            options={
                'verbose_name': 'Статья-Журнал',
                'verbose_name_plural': 'Статьи-Журналы',
                'unique_together': {('article', 'magazine')},
            },
        ),
        migrations.CreateModel(
            name='ArticleMathematician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleMath', to='main.article')),
                ('mathematician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mathematician', to='main.mathematician')),
            ],
            options={
                'verbose_name': 'Статья-Математик',
                'verbose_name_plural': 'Статьи-Математики',
                'unique_together': {('article', 'mathematician')},
            },
        ),
    ]
