# Generated by Django 3.1.7 on 2021-05-31 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210531_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год написания статьи'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска журнала'),
        ),
    ]
